"""Nuked migrations :v

Revision ID: d588346e0112
Revises: 
Create Date: 2023-11-25 00:12:31.330617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd588346e0112'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('leetcode_integration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('pairing',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'thread_id', 'user_id')
    )
    op.create_table('schedule',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_Monday', sa.Boolean(), nullable=False),
    sa.Column('available_Tuesday', sa.Boolean(), nullable=False),
    sa.Column('available_Wednesday', sa.Boolean(), nullable=False),
    sa.Column('available_Thursday', sa.Boolean(), nullable=False),
    sa.Column('available_Friday', sa.Boolean(), nullable=False),
    sa.Column('available_Saturday', sa.Boolean(), nullable=False),
    sa.Column('available_Sunday', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('schedule_adjustment',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_adjustment')
    op.drop_table('schedule')
    op.drop_table('pairing')
    op.drop_table('channel')
    # ### end Alembic commands ###
