"""nuked

Revision ID: fab85b27c1d3
Revises: 
Create Date: 2023-11-25 23:32:30.908140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab85b27c1d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel',
    sa.Column('guild_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('leetcode_integration', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_table('pairing',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sa.Integer(), nullable=False),
    sa.Column('user_1_id', sa.Integer(), nullable=False),
    sa.Column('user_2_id', sa.Integer(), nullable=False),
    sa.Column('user_3_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('channel_id', 'thread_id')
    )
    op.create_table('schedule',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('available_0', sa.Boolean(), nullable=False),
    sa.Column('available_1', sa.Boolean(), nullable=False),
    sa.Column('available_2', sa.Boolean(), nullable=False),
    sa.Column('available_3', sa.Boolean(), nullable=False),
    sa.Column('available_4', sa.Boolean(), nullable=False),
    sa.Column('available_5', sa.Boolean(), nullable=False),
    sa.Column('available_6', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id')
    )
    op.create_table('skip',
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('channel_id', 'user_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skip')
    op.drop_table('schedule')
    op.drop_table('pairing')
    op.drop_table('channel')
    # ### end Alembic commands ###
